
spin_manifest_version = 2

[application]
name = "info-on-arrival-service"
version = "0.1.0"
authors = ["Albergue Del Carrascalejo"]

[variables]
database_url = { required = true }
neon_database_url = { required = true }
google_places_api_key = { required = false }
log_level = { default = "info" }

[[trigger.http]]
route = "/..."
component = "info-on-arrival-service"

[component.info-on-arrival-service]
source = "target/wasm32-wasi/release/info_on_arrival_service.wasm"
allowed_outbound_hosts = [
    "https://maps.googleapis.com",
    "https://turismomerida.org",
    "https://radiotaximerida.es",
    "https://*.neon.tech"
]

[component.info-on-arrival-service.build]
command = "cargo build --target wasm32-wasi --release"

[component.info-on-arrival-service.variables]
database_url = "{{ database_url }}"
neon_database_url = "{{ neon_database_url }}"
google_places_api_key = "{{ google_places_api_key }}"
log_level = "{{ log_level }}"

[component.info-on-arrival-service.key_value_stores]
default = { label = "info-kv" }
