[install]
auto = "auto"

[run]
bun = true

[workspace]
packages = [
  "apps/*",
  "packages/*"
]

[workspace.dependencies]
react = "^18.3.1"
react-dom = "^18.3.1"

[workspace.devDependencies]
"@types/react" = "^18.3.16"
"@types/react-dom" = "^18.3.5"
"@vitejs/plugin-react" = "^4.3.4"
vite = "^6.0.3"
vitest = "^2.1.8"