version: '3'

vars:
  NODE_VERSION: "22"

env:
  NODE_ENV: development

tasks:
  install:
    desc: Install dependencies for all packages
    cmds:
      - bun install

  dev:
    desc: Start development servers for all microfrontends
    cmds:
      - bun run --filter="*" dev

  build:
    desc: Build all microfrontends
    cmds:
      - bun run --filter="*" build

  test:
    desc: Run tests for all packages
    cmds:
      - bun run --filter="*" test

  lint:
    desc: Lint all packages
    cmds:
      - bun run --filter="*" lint

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf apps/*/dist packages/*/dist

  build:spin:
    desc: Build for Spin deployment
    cmds:
      - task: build
      - mkdir -p dist
      - cp -r apps/*/dist/* dist/

  serve:spin:
    desc: Serve built microfrontends for Spin
    deps: [build:spin]
    cmds:
      - echo "Microfrontends ready for Spin deployment in dist/"