sonar.projectKey=guillermolam_AlbergueMunicipalCarrascalejo
sonar.organization=guillermolam
sonar.sources=frontend/src,backend,gateway,infra
sonar.exclusions=**/dist/**,**/target/**,**/node_modules/**,GIS/**,frontend/public/**,tests/infrastructure/docker/**
