spin_manifest_version = 2

[application]
name = "albergue-gateway"
version = "1.0.0"
description = "Albergue Gateway Only"

[variables]
gateway_config_path = { default = "/config/gateway.toml" }
redis_address = { required = true }

[[trigger.http]]
route = "/api/..."
component = "gateway"

[component.gateway]
source = "gateway/target/wasm32-wasip2/release/api_gateway.wasm"
allowed_outbound_hosts = ["redis://*"]
key_value_stores = ["default"]
files = [{ source = "gateway/api-gateway/config", destination = "/config" }]

[component.gateway.variables]
gateway_config_path = "{{ gateway_config_path }}"
redis_address = "{{ redis_address }}"