
# Runtime configuration for Spin services
# This file defines KV store labels and their purposes

[key_value_stores]

[key_value_stores.booking-kv]
type = "spin"
description = "Key-value store for booking data caching and session management"

[key_value_stores.notification-kv]
type = "spin"
description = "Key-value store for notification queues and delivery tracking"

[key_value_stores.reviews-kv]
type = "spin"
description = "Key-value store for review caching and moderation flags"

[key_value_stores.security-kv]
type = "spin"
description = "Key-value store for security tokens and rate limiting counters"

[key_value_stores.validation-kv]
type = "spin"
description = "Key-value store for OCR results caching and validation history"

[key_value_stores.info-kv]
type = "spin"
description = "Key-value store for scraped content caching and update timestamps"

[key_value_stores.location-kv]
type = "spin"
description = "Key-value store for location data and geocoding results"

[key_value_stores.rate-limiter-kv]
type = "spin"
description = "Key-value store for rate limiting counters and client tracking"
