
spin_manifest_version = 2

[application]
name = "validation-service"
version = "0.1.0"
authors = ["Albergue Del Carrascalejo"]

[variables]
database_url = { required = true }
tesseract_data_path = { default = "/usr/share/tessdata" }
lambda_ocr_url = { required = false }
log_level = { default = "info" }

[[trigger.http]]
route = "/..."
component = "validation-service"

[component.validation-service]
source = "target/wasm32-wasi/release/validation_service.wasm"
allowed_outbound_hosts = ["https://*.amazonaws.com", "https://*.neon.tech"]

[component.validation-service.build]
command = "cargo build --target wasm32-wasi --release"

[component.validation-service.variables]
database_url = "{{ database_url }}"
tesseract_data_path = "{{ tesseract_data_path }}"
lambda_ocr_url = "{{ lambda_ocr_url }}"
log_level = "{{ log_level }}"

[component.validation-service.key_value_stores]
default = { label = "validation-kv" }
