name = "retto-ocr-worker"
main = "src/index.ts"
compatibility_date = "2026-04-12"
compatibility_flags = ["nodejs_compat"]

account_id = "798e36259a38e6217cc9987ce0bf1316"

# Required: tell wrangler how to handle .wasm and .onnx files
[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[[rules]]
type = "Data"
globs = ["**/*.onnx"]

[env.preview]

[env.production]