/// <reference types="astro/client" />
/// <reference types="@clerk/astro/types" />
/// <reference path="../worker-configuration.d.ts" />

// ---------------------------------------------------------------------------
// Cloudflare Worker runtime environment
// Bindings are generated by `wrangler types` into worker-configuration.d.ts
//
// Astro v6 + @astrojs/cloudflare v13+:
//   - Astro.locals.runtime.env is REMOVED
//   - Use `import { env } from "cloudflare:workers"` for CF bindings
//   - Astro.locals.cfContext replaces locals.runtime.ctx
// ---------------------------------------------------------------------------

/** Minimal Cloudflare Fetcher / Service-binding interface. */
interface CloudflareServiceBinding {
  fetch(request: Request): Promise<Response>;
}

/**
 * Augment the auto-generated `Env` with bindings not yet tracked by
 * `wrangler types` (e.g. OCR_SERVICE, which requires the ocr-service to be
 * deployed before `wrangler types` picks it up).
 */
interface Env {
  OCR_SERVICE?: CloudflareServiceBinding;
}

// In @astrojs/cloudflare v13+, Runtime only exposes cfContext.
type Runtime = import('@astrojs/cloudflare').Runtime;

declare namespace App {
  // Merged with Runtime and Clerk's locals so all bindings are typed correctly.
  interface Locals extends Runtime {
    /** Authenticated user — null when role is 'guest'. */
    user: { id: string; email: string; name: string } | null;
    /** Coarse-grained role: 'admin' set via Clerk publicMetadata.role. */
    role: 'admin' | 'pilgrim' | 'guest';
    /** Always null — session is managed by Clerk cookies. */
    sessionToken: string | null;
  }
}
