spin_manifest_version = 2

[application]
name = "country-cache-service"
version = "0.1.0"

[variables]
redis_url = { required = true }

[[trigger.http]]
route = "/countries/..."
component = "country-cache"

[component.country-cache]
source = "target/wasm32-wasi/release/country_cache_service.wasm"
allowed_outbound_hosts = [
    "redis://*",
]

[component.country-cache.test]
command = "cargo test --no-run"

[component.country-cache.coverage]
command = "cargo tarpaulin --test-threads 1 --skip-clean"

[component.country-cache.variables]
redis_url = "{{ redis_url }}"

[component.country-cache.build]
command = "cargo build --target wasm32-wasi --release"